### PR TITLE
async -> asynchronous for clarity, closes #31

### LINKED ISSUE #31: global: rename async argument
Avoid confusion with `async` keyword: https://docs.python.org/3/reference/compound_stmts.html#async-def

### PR DESCRIPTION
**Pull request by cglewis**

### CODE REVIEW

**Comment by jirikuncar** [comment]
@cglewis thanks for the improvement! Please check [contributing guidelines](https://github.com/inveniosoftware/invenio-github/blob/master/CONTRIBUTING.rst#get-started) (point 6 - commit messages) or just see *inveniosoftware* organization style from `git log` (alternatively I can amend the commit message while merging).

- [ ] Please add yourself to `AUTHORS`.
- [ ] Please reply if you agree to donate this (and any future) contributions to *inveniosoftware* organization under the terms of the package FLOSS license.

Thanks again and welcome to Invenio community!

**Comment by cglewis** [comment]
updated and agree !

**Comment by cglewis** [comment]
@lnielsen do I need to make any other changes for this?

**Comment by lnielsen** [comment]
LGTM

**Comment by lnielsen** [comment]
@slint Please check if this requires updates on Zenodo.

**Pull request merged**
